import type { AiOverrideConfig } from "./config";

export interface AiMarkerMatch {
  label: string;
  source: "message" | "author" | "committer" | "config";
}

export interface AiDetection {
  isAi: boolean;
  confidence: number;
  matches: AiMarkerMatch[];
}

export const aiMarkerLabels = [
  "Co-authored-by trailer names Claude, Anthropic, OpenAI, Codex, Copilot, Cursor, Devin, or an agent",
  "Commit author or committer looks like an AI agent or bot",
  "Commit message contains explicit AI-assisted labels such as ai-assisted, claude-code, cursor, codex, or copilot",
  "Configured GitHub usernames and PR numbers are counted as AI with 100% confidence"
];

const messagePatterns: Array<{ label: string; pattern: RegExp }> = [
  {
    label: "co-author trailer mentions AI agent",
    pattern:
      /^co-authored-by:.*(claude|anthropic|openai|codex|copilot|cursor|devin|agent)/gim
  },
  {
    label: "explicit AI-assisted marker",
    pattern:
      /\b(ai-assisted|agent-authored|claude-code|claude code|cursor|codex|copilot|devin)\b/i
  },
  {
    label: "generated-by AI marker",
    pattern:
      /\b(generated by|authored by|written by)\s+(claude|codex|copilot|cursor|devin|openai|anthropic)\b/i
  }
];

const identityPatterns: Array<{ label: string; pattern: RegExp }> = [
  {
    label: "AI bot identity",
    pattern:
      /\b(claude|anthropic|openai|codex|copilot|cursor|devin|agent|bot)\b/i
  }
];

const uniqueMatches = (matches: AiMarkerMatch[]) => {
  const seen = new Set<string>();

  return matches.filter((match) => {
    const key = `${match.source}:${match.label}`;

    if (seen.has(key)) {
      return false;
    }

    seen.add(key);
    return true;
  });
};

const normalizedSet = (values: readonly string[]) =>
  new Set(values.map((value) => value.toLowerCase()));

export const githubUsernamesForIdentity = (input: {
  name: string;
  email: string;
}) => {
  const usernames = new Set<string>();
  const name = input.name.trim().toLowerCase();

  if (name.length > 0) {
    usernames.add(name);
  }

  const noreplyMatch = input.email
    .trim()
    .toLowerCase()
    .match(/^(?:\d+\+)?([^@]+)@users\.noreply\.github\.com$/);

  if (noreplyMatch?.[1]) {
    usernames.add(noreplyMatch[1]);
  }

  return [...usernames];
};

export const detectAiAttribution = (input: {
  message: string;
  authorName: string;
  authorEmail: string;
  committerName: string;
  committerEmail: string;
  prNumber: number | null;
  overrides: AiOverrideConfig;
}): AiDetection => {
  const matches: AiMarkerMatch[] = [];
  const configuredUsernames = normalizedSet(input.overrides.githubUsernames);
  const configuredPrNumbers = new Set(input.overrides.prNumbers);

  if (input.prNumber !== null && configuredPrNumbers.has(input.prNumber)) {
    matches.push({
      label: `configured PR #${input.prNumber}`,
      source: "config"
    });
  }

  for (const marker of messagePatterns) {
    if (marker.pattern.test(input.message)) {
      matches.push({ label: marker.label, source: "message" });
    }
  }

  const authorIdentity = `${input.authorName} ${input.authorEmail}`;
  const committerIdentity = `${input.committerName} ${input.committerEmail}`;
  const authorGithubUsernames = githubUsernamesForIdentity({
    name: input.authorName,
    email: input.authorEmail
  });
  const committerGithubUsernames = githubUsernamesForIdentity({
    name: input.committerName,
    email: input.committerEmail
  });

  for (const username of authorGithubUsernames) {
    if (configuredUsernames.has(username)) {
      matches.push({
        label: `configured GitHub username ${username}`,
        source: "config"
      });
    }
  }

  for (const username of committerGithubUsernames) {
    if (configuredUsernames.has(username)) {
      matches.push({
        label: `configured GitHub username ${username}`,
        source: "config"
      });
    }
  }

  for (const marker of identityPatterns) {
    if (marker.pattern.test(authorIdentity)) {
      matches.push({ label: marker.label, source: "author" });
    }

    if (marker.pattern.test(committerIdentity)) {
      matches.push({ label: marker.label, source: "committer" });
    }
  }

  const unique = uniqueMatches(matches);
  const hasConfigMarker = unique.some((match) => match.source === "config");
  const hasStrongMessageMarker = unique.some(
    (match) =>
      match.source === "message" &&
      (match.label.includes("co-author") ||
        match.label.includes("explicit") ||
        match.label.includes("generated"))
  );
  const confidence =
    unique.length === 0 ? 0 : hasConfigMarker ? 1 : hasStrongMessageMarker ? 0.86 : 0.68;

  return {
    isAi: unique.length > 0,
    confidence,
    matches: unique
  };
};
